export const data = [
    {
        "sector": "Ingenieurwesen",
        "educationStatus": "Universität",
        "foreignLanguage": "Eng",
        "dirivingLicence": "B,A",
        "birthDate": "1994-06-10T00:00:00.000Z",
        "gender": "M",
        "maritalStatus": "Ledig",
        "workingLocation": "Berlin",
        "schengen": "Ja",
        "enabled": "Ja"
    },
    {
        "sector": "Ingenieurwesen",
        "educationStatus": "Universität",
        "foreignLanguage": "Eng,De",
        "dirivingLicence": "B",
        "birthDate": "1994-06-02T00:00:00.000Z",
        "gender": "M",
        "maritalStatus": "Ledig",
        "workingLocation": "Berlin",
        "schengen": "Ja",
        "enabled": "Ja"
    },
    {
        "sector": "Ingenieurwesen",
        "educationStatus": "Universität",
        "foreignLanguage": "De",
        "dirivingLicence": "B",
        "birthDate": "1994-06-03T00:00:00.000Z",
        "gender": "M",
        "maritalStatus": "Ledig",
        "workingLocation": "Berlin",
        "schengen": "Ja",
        "enabled": "Ja"
    },
    {
        "sector": "Handwerk",
        "educationStatus": "Ausbildung",
        "foreignLanguage": "De",
        "dirivingLicence": "B",
        "birthDate": "1994-06-04T00:00:00.000Z",
        "gender": "M",
        "maritalStatus": "Ledig",
        "workingLocation": "Berlin",
        "schengen": "Ja",
        "enabled": "Nein"
    },
    {
        "sector": "Handwerk",
        "educationStatus": "Ausbildung",
        "foreignLanguage": "De",
        "dirivingLicence": "B",
        "birthDate": "1994-06-05T00:00:00.000Z",
        "gender": "M",
        "maritalStatus": "Ledig",
        "workingLocation": "Berlin",
        "schengen": "Ja",
        "enabled": "Nein"
    },
    {
        "sector": "Handwerk",
        "educationStatus": "Ausbildung",
        "foreignLanguage": "Keine",
        "dirivingLicence": "B",
        "birthDate": "1994-06-06T00:00:00.000Z",
        "gender": "M",
        "maritalStatus": "Ledig",
        "workingLocation": "Berlin",
        "schengen": "Ja",
        "enabled": "Nein"
    },
    {
        "sector": "Gesundheit",
        "educationStatus": "Universität",
        "foreignLanguage": "Eng",
        "dirivingLicence": "B",
        "birthDate": "1986-06-07T00:00:00.000Z",
        "gender": "F",
        "maritalStatus": "Ledig",
        "workingLocation": "Berlin",
        "schengen": "Ja",
        "enabled": "Nein"
    },
    {
        "sector": "Gesundheit",
        "educationStatus": "Universität",
        "foreignLanguage": "Eng",
        "dirivingLicence": "B",
        "birthDate": "1997-06-08T00:00:00.000Z",
        "gender": "F",
        "maritalStatus": "Ledig",
        "workingLocation": "Berlin",
        "schengen": "Ja",
        "enabled": "Nein"
    },
    {
        "sector": "Gesundheit",
        "educationStatus": "Universität",
        "foreignLanguage": "Eng",
        "dirivingLicence": "B",
        "birthDate": "2000-06-09T00:00:00.000Z",
        "gender": "M",
        "maritalStatus": "Ledig",
        "workingLocation": "Berlin",
        "schengen": "Ja",
        "enabled": "Nein"
    },
    {
        "sector": "Pflege",
        "educationStatus": "Ausbildung",
        "foreignLanguage": "Eng,De",
        "dirivingLicence": "B",
        "birthDate": "2001-06-10T00:00:00.000Z",
        "gender": "F",
        "maritalStatus": "Verheiratet",
        "workingLocation": "Köln",
        "schengen": "Ja",
        "enabled": "Nein"
    },
    {
        "sector": "Pflege",
        "educationStatus": "Ausbildung",
        "foreignLanguage": "Eng,De",
        "dirivingLicence": "Kein",
        "birthDate": "1994-06-11T00:00:00.000Z",
        "gender": "F",
        "maritalStatus": "Verheiratet",
        "workingLocation": "Köln",
        "schengen": "Ja",
        "enabled": "Nein"
    },
    {
        "sector": "Pflege",
        "educationStatus": "Ausbildung",
        "foreignLanguage": "De",
        "dirivingLicence": "Kein",
        "birthDate": "1994-06-12T00:00:00.000Z",
        "gender": "M",
        "maritalStatus": "Verheiratet",
        "workingLocation": "Köln",
        "schengen": "Ja",
        "enabled": "Nein"
    },
    {
        "sector": "Bauwesen",
        "educationStatus": "Ausbildung",
        "foreignLanguage": "De",
        "dirivingLicence": "Kein",
        "birthDate": "1994-06-13T00:00:00.000Z",
        "gender": "M",
        "maritalStatus": "Verheiratet",
        "workingLocation": "Köln",
        "schengen": "Nein",
        "enabled": "Nein"
    },
    {
        "sector": "Bauwesen",
        "educationStatus": "Ausbildung",
        "foreignLanguage": "De",
        "dirivingLicence": "Kein",
        "birthDate": "1990-06-14T00:00:00.000Z",
        "gender": "M",
        "maritalStatus": "Verheiratet",
        "workingLocation": "Köln",
        "schengen": "Nein",
        "enabled": "Nein"
    },
    {
        "sector": "Bauwesen",
        "educationStatus": "Ausbildung",
        "foreignLanguage": "De",
        "dirivingLicence": "A",
        "birthDate": "1994-06-15T00:00:00.000Z",
        "gender": "M",
        "maritalStatus": "Verheiratet",
        "workingLocation": "Köln",
        "schengen": "Nein",
        "enabled": "Nein"
    },
    {
        "sector": "Gastronomie",
        "educationStatus": "Ausbildung",
        "foreignLanguage": "De",
        "dirivingLicence": "A",
        "birthDate": "1994-06-16T00:00:00.000Z",
        "gender": "F",
        "maritalStatus": "Verheiratet",
        "workingLocation": "Köln",
        "schengen": "Nein",
        "enabled": "Nein"
    },
    {
        "sector": "Gastronomie",
        "educationStatus": "Ausbildung",
        "foreignLanguage": "De",
        "dirivingLicence": "A",
        "birthDate": "1994-06-17T00:00:00.000Z",
        "gender": "F",
        "maritalStatus": "Verheiratet",
        "workingLocation": "Köln",
        "schengen": "Nein",
        "enabled": "Nein"
    },
    {
        "sector": "Gastronomie",
        "educationStatus": "Ausbildung",
        "foreignLanguage": "Eng",
        "dirivingLicence": "B,A",
        "birthDate": "1994-06-18T00:00:00.000Z",
        "gender": "M",
        "maritalStatus": "Verheiratet",
        "workingLocation": "Berlin, Köln",
        "schengen": "Nein",
        "enabled": "Nein"
    },
    {
        "sector": "Sicherheit",
        "educationStatus": "Ausbildung",
        "foreignLanguage": "Keine",
        "dirivingLicence": "B,A",
        "birthDate": "1994-06-19T00:00:00.000Z",
        "gender": "M",
        "maritalStatus": "Verheiratet",
        "workingLocation": "Berlin, Köln",
        "schengen": "Nein",
        "enabled": "Nein"
    },
    {
        "sector": "Sicherheit",
        "educationStatus": "Ausbildung",
        "foreignLanguage": "Eng",
        "dirivingLicence": "B,A",
        "birthDate": "1994-06-20T00:00:00.000Z",
        "gender": "M",
        "maritalStatus": "Verheiratet",
        "workingLocation": "Berlin, Köln",
        "schengen": "Nein",
        "enabled": "Ja"
    },
    {
        "sector": "Sicherheit",
        "educationStatus": "Ausbildung",
        "foreignLanguage": "De",
        "dirivingLicence": "B,A",
        "birthDate": "1994-06-21T00:00:00.000Z",
        "gender": "M",
        "maritalStatus": "Verheiratet",
        "workingLocation": "Berlin, Köln",
        "schengen": "Nein",
        "enabled": "Ja"
    }
]

